# Generated by Django 4.2.6 on 2023-10-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviditor', '0002_imagemodel_alter_audiomodel_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='audio',
            field=models.FileField(upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
