# Generated by Django 4.2.6 on 2023-10-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviditor', '0006_alter_audiomodel_name_alter_audiomodel_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False)),
                ('video', models.FileField(upload_to='videos')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
