# Generated by Django 4.2.6 on 2023-10-21 22:36

from django.conf import settings
from django.db import migrations, models
import moviditor.logic.users_logic


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviditor', '0007_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomodel',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=models.SET(moviditor.logic.users_logic.get_deleted_stand_in_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomodel',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=models.SET(moviditor.logic.users_logic.get_deleted_stand_in_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
